# Generated by Django 5.0.2 on 2024-02-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_message_delete_messae'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YourName', models.CharField(max_length=200)),
                ('YourEmail', models.EmailField(max_length=254)),
                ('YourPhone', models.IntegerField(max_length=200)),
                ('AppointmentDate', models.DateField()),
                ('Department', models.CharField(max_length=200)),
                ('Doctor', models.CharField(max_length=200)),
                ('Message', models.TextField()),
            ],
        ),
    ]
